[theme]
primaryColor = "#1B8354"
backgroundColor = "#F2F7F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A2E21"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 500
