[theme]
primaryColor = "#1B8354"
backgroundColor = "#F3F4F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#161616"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false
maxUploadSize = 50
maxMessageSize = 50

[browser]
gatherUsageStats = false
